#!/bin/bash

install() {
    echo "Installing ..."
    go install gopost/main/
}

run() {
    echo "GoPost! ..."
    bin/main
}

startdb() {
    MONGOPID=$(cat /usr/local/var/mongodb/mongod.lock)

    if [[ -z $MONGOPID ]]
    then
        echo "Starting database ..."
        mongod run --config /usr/local/etc/mongod.conf &
    else
        echo "Um ... mongod's already up."
    fi
}

stopdb() {
    MONGOPID=$(cat /usr/local/var/mongodb/mongod.lock)

    if [[ -z $MONGOPID ]]
    then
        echo "No mongo instance running."
    else
        echo "Stopping database ... hold on ..."
        kill -15 $MONGOPID
        wait

        if [[ -z $(pgrep mongod) ]]
        then
            echo "Mongo only pawn in game of life."
        else
            echo "Mongo still up!"
        fi
    fi
}

test() {
    echo "Running test ..."
    go test gopost/content/post
}

case "$1" in
    "install" ) install
        ;;
    "run"     ) run
        ;;
    "startdb" ) startdb
        ;;
    "stopdb"  ) stopdb
        ;;
    "test"    ) test
        ;;
esac

exit 0
