#!/bin/bash

MONGOPID=$(cat /usr/local/var/mongodb/mongod.lock)

build() {
    echo "Building ..."
    go install gopost/main/
}

run() {
    if [[ -z $MONGOPID ]]
    then
        echo "No mongo instance running."
    else
        build
        echo "GoPost! ..."
        bin/main
    fi
}

startdb() {
    if [[ -z $MONGOPID ]]
    then
        echo "Starting database ..."
        mongod run --config /usr/local/etc/mongod.conf &
    else
        echo "Um ... mongod's already up."
    fi
}

stopdb() {
    if [[ -z $MONGOPID ]]
    then
        echo "No mongo instance running."
    else
        echo "Stopping database ... hold on ..."
        kill -15 $MONGOPID
        wait

        if [[ -z $(pgrep mongod) ]]
        then
            echo "Mongo only pawn in game of life."
        else
            echo "Mongo still up!"
        fi
    fi
}

runtests() {
    if [[ -z $MONGOPID ]]
    then
        echo "Can't create a test database."
        echo "No mongo instance, no tests, forget it."

        echo
        read -p "Should I start mongo? " -n 1 -r

        if [[ $REPLY =~ ^[Yy]$ ]]
        then
            startdb
        fi
    else
        echo "Running tests ..."
        build

        echo "Running post tests."
        go test gopost/content/post
    fi
}

case "$1" in
    "install" ) build
        ;;
    "run"     ) run
        ;;
    "startdb" ) startdb
        ;;
    "stopdb"  ) stopdb
        ;;
    "test"    ) runtests
        ;;
esac

exit 0
